#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
  path: /
  controller: App\Controller\DefaultController::index

hello:
  path: /api/hello
  controller: App\Controller\DefaultController::hello
