[tool.poetry]
name = "sandbox-loadtest"
version = "0.1.0"
description = ""
authors = ["Sean Quinn <swquinn@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
locust = "^1.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
